services:
  postgres:
    image: postgres:latest
    container_name: user-postgres-1
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      TZ: Asia/Kolkata   # OS timezone only, safe
    ports:
      - "5432:5432"
